variables:
        IMAGE_NAME: nicoleketch/demo-gitlab-cicd
        IMAGE_TAG: python-app-1.0
stages:
    - test
    - build

run_tests:
    stage: test
    image: python:3.9-slim-buster
    before_script:
        - apt-get -yqq update && apt-get install -yqq git && apt-get install -yqq make
        - pip install -r src/requirements.txt
    script: 
        - make test
build_image:
    stage: build
    image: docker:25.0.3
    services:
        - docker:25.0.3-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - docker login -u $REGISTRY_USER -p $REGISTRY_PW
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG . 
        - docker push $IMAGE_NAME:$IMAGE_TAG

