run_tests:
    image: python:3.9-slim-buster
    before_script:
        - apt-get -yqq update && apt-get install -yqq git && apt-get install -yqq make
        - pip install -r requirements.txt
    script: 
        - make test
